version: "3.7"

services:
    api:
        build:
            context: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
